# Generated by Django 6.0.4 on 2026-04-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
