# Generated by Django 6.0.4 on 2026-04-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_chunk_count_document_summary_generated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchquery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Research Query', 'verbose_name_plural': 'Research Queries'},
        ),
        migrations.AddField(
            model_name='researchquery',
            name='response_length',
            field=models.IntegerField(default=0),
        ),
    ]
