# Generated by Django 6.0.4 on 2026-04-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_researchquery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='court_name',
            field=models.CharField(choices=[('delhi high court', 'Delhi High Court'), ('bombay high court', 'Bombay High Court'), ('culcutta high court', 'Culcutta High Court'), ('madras high court', 'Madras High Court')], default='other', max_length=200),
        ),
    ]
