# Generated by Django 6.0.4 on 2026-04-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_court_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='court_name',
            field=models.CharField(choices=[('delhi high court', 'Delhi High Court'), ('bombay high court', 'Bombay High Court'), ('culcutta high court', 'Culcutta High Court'), ('madras high court', 'Madras High Court'), ('other', 'Other')], default='other', max_length=200),
        ),
    ]
