# Generated by Django 6.0.4 on 2026-04-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_court_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('target_language', models.CharField(choices=[('hi', 'Hindi'), ('ta', 'Tamil')], max_length=5)),
                ('char_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Translation Cache',
                'verbose_name_plural': 'Translation Cache',
                'unique_together': {('content_hash', 'target_language')},
            },
        ),
    ]
